// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/Features/auth/domain/use_cases/signup_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/core/base_response/base_response.dart' as _i4;
import 'package:flowers_app/Features/auth/data/models/signup_models/signup_request.dart'
    as _i6;
import 'package:flowers_app/Features/auth/domain/auth_repo_contract/auth_repo_contract.dart'
    as _i2;
import 'package:flowers_app/Features/auth/domain/entities/login_entity.dart'
    as _i8;
import 'package:flowers_app/Features/auth/domain/entities/signup_entity.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthRepoContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepoContract extends _i1.Mock implements _i2.AuthRepoContract {
  MockAuthRepoContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.SignupEntity>> signUp(
    _i6.SignupRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [request]),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.SignupEntity>>.value(
              _i7.dummyValue<_i4.BaseResponse<_i5.SignupEntity>>(
                this,
                Invocation.method(#signUp, [request]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.SignupEntity>>);

  @override
  _i3.Future<_i4.BaseResponse<_i8.LoginEntity>> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [email, password]),
            returnValue: _i3.Future<_i4.BaseResponse<_i8.LoginEntity>>.value(
              _i7.dummyValue<_i4.BaseResponse<_i8.LoginEntity>>(
                this,
                Invocation.method(#login, [email, password]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i8.LoginEntity>>);
}
