// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbOPgHaVrUfcvtZZex_ZPW3zGstDjnOcI',
    appId: '1:286117840504:web:75ea50506ef3f235718f8d',
    messagingSenderId: '286117840504',
    projectId: 'flowers-app-630b3',
    authDomain: 'flowers-app-630b3.firebaseapp.com',
    storageBucket: 'flowers-app-630b3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDZE5xjnQvlBtiqQ4d0GntQ219NRc7HFk',
    appId: '1:286117840504:android:cdbbfc3a027bfdc2718f8d',
    messagingSenderId: '286117840504',
    projectId: 'flowers-app-630b3',
    storageBucket: 'flowers-app-630b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDumiwBbsxuSrFRTYAu_ZR5StkzxK8VtB4',
    appId: '1:286117840504:ios:734249da0fc4bc5a718f8d',
    messagingSenderId: '286117840504',
    projectId: 'flowers-app-630b3',
    storageBucket: 'flowers-app-630b3.firebasestorage.app',
    iosBundleId: 'com.example.flowersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDumiwBbsxuSrFRTYAu_ZR5StkzxK8VtB4',
    appId: '1:286117840504:ios:734249da0fc4bc5a718f8d',
    messagingSenderId: '286117840504',
    projectId: 'flowers-app-630b3',
    storageBucket: 'flowers-app-630b3.firebasestorage.app',
    iosBundleId: 'com.example.flowersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbOPgHaVrUfcvtZZex_ZPW3zGstDjnOcI',
    appId: '1:286117840504:web:fe293db00480c0f5718f8d',
    messagingSenderId: '286117840504',
    projectId: 'flowers-app-630b3',
    authDomain: 'flowers-app-630b3.firebaseapp.com',
    storageBucket: 'flowers-app-630b3.firebasestorage.app',
  );
}