// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG1pkP_KEJr7KEFx8zLrRiW6k7HWrlQyE',
    appId: '1:183581153519:web:a595ba99d710ff4d9be31a',
    messagingSenderId: '183581153519',
    projectId: 'tracking-app-a9e77',
    authDomain: 'tracking-app-a9e77.firebaseapp.com',
    storageBucket: 'tracking-app-a9e77.firebasestorage.app',
    measurementId: 'G-EXGRTBLSCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUfAE__1dHLsY6Wr_mGx-BBNE0KJpbO6c',
    appId: '1:183581153519:android:edafed20ea95a0659be31a',
    messagingSenderId: '183581153519',
    projectId: 'tracking-app-a9e77',
    storageBucket: 'tracking-app-a9e77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Tfn0oFoyBPH_0DgEq9cFeRYi_QhqmbA',
    appId: '1:183581153519:ios:b2e6b9803b495a239be31a',
    messagingSenderId: '183581153519',
    projectId: 'tracking-app-a9e77',
    storageBucket: 'tracking-app-a9e77.firebasestorage.app',
    iosBundleId: 'com.example.flowersApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Tfn0oFoyBPH_0DgEq9cFeRYi_QhqmbA',
    appId: '1:183581153519:ios:b2e6b9803b495a239be31a',
    messagingSenderId: '183581153519',
    projectId: 'tracking-app-a9e77',
    storageBucket: 'tracking-app-a9e77.firebasestorage.app',
    iosBundleId: 'com.example.flowersApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG1pkP_KEJr7KEFx8zLrRiW6k7HWrlQyE',
    appId: '1:183581153519:web:4500ff4df1d89c0c9be31a',
    messagingSenderId: '183581153519',
    projectId: 'tracking-app-a9e77',
    authDomain: 'tracking-app-a9e77.firebaseapp.com',
    storageBucket: 'tracking-app-a9e77.firebasestorage.app',
    measurementId: 'G-06HV1P90T7',
  );

}