// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/Features/auth/api/auth_data_source_imple/auth_remote_data_source_imple_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:flowers_app/Features/auth/api/api_client/auth_api.dart' as _i7;
import 'package:flowers_app/Features/auth/data/models/forget_password/request/forget_password_request/forget_password_request.dart'
    as _i11;
import 'package:flowers_app/Features/auth/data/models/forget_password/request/reset_password_request/reset_password_request.dart'
    as _i13;
import 'package:flowers_app/Features/auth/data/models/forget_password/request/verify_password_request/verify_password_request.dart'
    as _i12;
import 'package:flowers_app/Features/auth/data/models/forget_password/responce/forget_password_responce.dart'
    as _i4;
import 'package:flowers_app/Features/auth/data/models/forget_password/responce/reset_password_responce.dart'
    as _i6;
import 'package:flowers_app/Features/auth/data/models/forget_password/responce/verify_password_responce.dart'
    as _i5;
import 'package:flowers_app/Features/auth/data/models/login_models/login_request.dart'
    as _i10;
import 'package:flowers_app/Features/auth/data/models/login_models/login_response.dart'
    as _i3;
import 'package:flowers_app/Features/auth/data/models/signup_models/signup_request.dart'
    as _i9;
import 'package:flowers_app/Features/auth/data/models/signup_models/signup_response.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSignupResponse_0 extends _i1.SmartFake
    implements _i2.SignupResponse {
  _FakeSignupResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponce_2 extends _i1.SmartFake
    implements _i4.ForgetPasswordResponce {
  _FakeForgetPasswordResponce_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyPasswordResponce_3 extends _i1.SmartFake
    implements _i5.VerifyPasswordResponce {
  _FakeVerifyPasswordResponce_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponce_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponce {
  _FakeResetPasswordResponce_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthApi extends _i1.Mock implements _i7.AuthApi {
  MockAuthApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.SignupResponse> signUp(_i9.SignupRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [request]),
            returnValue: _i8.Future<_i2.SignupResponse>.value(
              _FakeSignupResponse_0(
                this,
                Invocation.method(#signUp, [request]),
              ),
            ),
          )
          as _i8.Future<_i2.SignupResponse>);

  @override
  _i8.Future<_i3.LoginResponse> login(_i10.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i8.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(this, Invocation.method(#login, [request])),
            ),
          )
          as _i8.Future<_i3.LoginResponse>);

  @override
  _i8.Future<_i4.ForgetPasswordResponce> forgetPassword(
    _i11.ForgetPasswordRequest? forgetRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [forgetRequest]),
            returnValue: _i8.Future<_i4.ForgetPasswordResponce>.value(
              _FakeForgetPasswordResponce_2(
                this,
                Invocation.method(#forgetPassword, [forgetRequest]),
              ),
            ),
          )
          as _i8.Future<_i4.ForgetPasswordResponce>);

  @override
  _i8.Future<_i5.VerifyPasswordResponce> verifyPassword(
    _i12.VerifyPasswordRequest? verifyRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPassword, [verifyRequest]),
            returnValue: _i8.Future<_i5.VerifyPasswordResponce>.value(
              _FakeVerifyPasswordResponce_3(
                this,
                Invocation.method(#verifyPassword, [verifyRequest]),
              ),
            ),
          )
          as _i8.Future<_i5.VerifyPasswordResponce>);

  @override
  _i8.Future<_i6.ResetPasswordResponce> resetPassword(
    _i13.ResetPasswordRequest? resetRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [resetRequest]),
            returnValue: _i8.Future<_i6.ResetPasswordResponce>.value(
              _FakeResetPasswordResponce_4(
                this,
                Invocation.method(#resetPassword, [resetRequest]),
              ),
            ),
          )
          as _i8.Future<_i6.ResetPasswordResponce>);
}
