// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/Features/auth/data/auth_repo_imple/auth_repo_imple_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flowers_app/Features/auth/data/auth_data_source_contract/auth_remote_data_source_contract.dart'
    as _i4;
import 'package:flowers_app/Features/auth/data/models/login_models/login_request.dart'
    as _i7;
import 'package:flowers_app/Features/auth/data/models/login_models/login_response.dart'
    as _i3;
import 'package:flowers_app/Features/auth/data/models/signup_models/signup_request.dart'
    as _i6;
import 'package:flowers_app/Features/auth/data/models/signup_models/signup_response.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSignupResponse_0 extends _i1.SmartFake
    implements _i2.SignupResponse {
  _FakeSignupResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSourceContract extends _i1.Mock
    implements _i4.AuthRemoteDataSourceContract {
  MockAuthRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.SignupResponse> signUp(_i6.SignupRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [request]),
            returnValue: _i5.Future<_i2.SignupResponse>.value(
              _FakeSignupResponse_0(
                this,
                Invocation.method(#signUp, [request]),
              ),
            ),
          )
          as _i5.Future<_i2.SignupResponse>);

  @override
  _i5.Future<_i3.LoginResponse> login(_i7.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i5.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(this, Invocation.method(#login, [request])),
            ),
          )
          as _i5.Future<_i3.LoginResponse>);
}
