// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/Features/auth/data/auth_repo_imple/auth_repo_imple_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:flowers_app/Features/auth/data/auth_data_source_contract/auth_local_data_source_contract.dart'
    as _i14;
import 'package:flowers_app/Features/auth/data/auth_data_source_contract/auth_remote_data_source_contract.dart'
    as _i7;
import 'package:flowers_app/Features/auth/data/models/forget_password/request/forget_password_request/forget_password_request.dart'
    as _i11;
import 'package:flowers_app/Features/auth/data/models/forget_password/request/reset_password_request/reset_password_request.dart'
    as _i13;
import 'package:flowers_app/Features/auth/data/models/forget_password/request/verify_password_request/verify_password_request.dart'
    as _i12;
import 'package:flowers_app/Features/auth/data/models/forget_password/response/forget_password_response/forget_password_response.dart'
    as _i4;
import 'package:flowers_app/Features/auth/data/models/forget_password/response/reset_password_response/reset_password_response.dart'
    as _i6;
import 'package:flowers_app/Features/auth/data/models/forget_password/response/verify_password_response/verify_password_response.dart'
    as _i5;
import 'package:flowers_app/Features/auth/data/models/login_models/login_request.dart'
    as _i10;
import 'package:flowers_app/Features/auth/data/models/login_models/login_response.dart'
    as _i3;
import 'package:flowers_app/Features/auth/data/models/signup_models/signup_request.dart'
    as _i9;
import 'package:flowers_app/Features/auth/data/models/signup_models/signup_response.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignupResponse_0 extends _i1.SmartFake
    implements _i2.SignupResponse {
  _FakeSignupResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLoginResponse_1 extends _i1.SmartFake implements _i3.LoginResponse {
  _FakeLoginResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponse_2 extends _i1.SmartFake
    implements _i4.ForgetPasswordResponse {
  _FakeForgetPasswordResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVerifyPasswordResponse_3 extends _i1.SmartFake
    implements _i5.VerifyPasswordResponse {
  _FakeVerifyPasswordResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResetPasswordResponse_4 extends _i1.SmartFake
    implements _i6.ResetPasswordResponse {
  _FakeResetPasswordResponse_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSourceContract extends _i1.Mock
    implements _i7.AuthRemoteDataSourceContract {
  MockAuthRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i2.SignupResponse> signUp(_i9.SignupRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [request]),
            returnValue: _i8.Future<_i2.SignupResponse>.value(
              _FakeSignupResponse_0(
                this,
                Invocation.method(#signUp, [request]),
              ),
            ),
          )
          as _i8.Future<_i2.SignupResponse>);

  @override
  _i8.Future<_i3.LoginResponse> login(_i10.LoginRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#login, [request]),
            returnValue: _i8.Future<_i3.LoginResponse>.value(
              _FakeLoginResponse_1(this, Invocation.method(#login, [request])),
            ),
          )
          as _i8.Future<_i3.LoginResponse>);

  @override
  _i8.Future<_i4.ForgetPasswordResponse> forgetPassword(
    _i11.ForgetPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [request]),
            returnValue: _i8.Future<_i4.ForgetPasswordResponse>.value(
              _FakeForgetPasswordResponse_2(
                this,
                Invocation.method(#forgetPassword, [request]),
              ),
            ),
          )
          as _i8.Future<_i4.ForgetPasswordResponse>);

  @override
  _i8.Future<_i5.VerifyPasswordResponse> verifyPassword(
    _i12.VerifyPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyPassword, [request]),
            returnValue: _i8.Future<_i5.VerifyPasswordResponse>.value(
              _FakeVerifyPasswordResponse_3(
                this,
                Invocation.method(#verifyPassword, [request]),
              ),
            ),
          )
          as _i8.Future<_i5.VerifyPasswordResponse>);

  @override
  _i8.Future<_i6.ResetPasswordResponse> resetPassword(
    _i13.ResetPasswordRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [request]),
            returnValue: _i8.Future<_i6.ResetPasswordResponse>.value(
              _FakeResetPasswordResponse_4(
                this,
                Invocation.method(#resetPassword, [request]),
              ),
            ),
          )
          as _i8.Future<_i6.ResetPasswordResponse>);
}

/// A class which mocks [AuthLocalDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthLocalDataSourceContract extends _i1.Mock
    implements _i14.AuthLocalDataSourceContract {
  MockAuthLocalDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  _i8.Future<void> saveRememberMe(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#saveRememberMe, [value]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> getRememberMe() =>
      (super.noSuchMethod(
            Invocation.method(#getRememberMe, []),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> clearUserData() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserData, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}
