// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/Features/auth/presentation/sign_in/view_model/login_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowers_app/core/base_response/base_response.dart' as _i5;
import 'package:flowers_app/core/controller/session_controller.dart' as _i8;
import 'package:flowers_app/Features/auth/domain/entities/login_entity.dart'
    as _i2;
import 'package:flowers_app/Features/auth/domain/use_cases/guest_login_usecase.dart'
    as _i7;
import 'package:flowers_app/Features/auth/domain/use_cases/login_usecase.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLoginEntity_0 extends _i1.SmartFake implements _i2.LoginEntity {
  _FakeLoginEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUseCase extends _i1.Mock implements _i3.LoginUseCase {
  MockLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.BaseResponse<_i2.LoginEntity>> call({
    required String? email,
    required String? password,
    required bool? isRememberMe,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#call, [], {
              #email: email,
              #password: password,
              #isRememberMe: isRememberMe,
            }),
            returnValue: _i4.Future<_i5.BaseResponse<_i2.LoginEntity>>.value(
              _i6.dummyValue<_i5.BaseResponse<_i2.LoginEntity>>(
                this,
                Invocation.method(#call, [], {
                  #email: email,
                  #password: password,
                  #isRememberMe: isRememberMe,
                }),
              ),
            ),
          )
          as _i4.Future<_i5.BaseResponse<_i2.LoginEntity>>);
}

/// A class which mocks [GuestLoginUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGuestLoginUseCase extends _i1.Mock implements _i7.GuestLoginUseCase {
  MockGuestLoginUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.LoginEntity> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<_i2.LoginEntity>.value(
              _FakeLoginEntity_0(this, Invocation.method(#call, [])),
            ),
          )
          as _i4.Future<_i2.LoginEntity>);
}

/// A class which mocks [SessionController].
///
/// See the documentation for Mockito's code generation for more information.
class MockSessionController extends _i1.Mock implements _i8.SessionController {
  MockSessionController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<void> get onSessionExpired =>
      (super.noSuchMethod(
            Invocation.getter(#onSessionExpired),
            returnValue: _i4.Stream<void>.empty(),
          )
          as _i4.Stream<void>);

  @override
  _i4.Stream<void> get onLogin =>
      (super.noSuchMethod(
            Invocation.getter(#onLogin),
            returnValue: _i4.Stream<void>.empty(),
          )
          as _i4.Stream<void>);

  @override
  _i4.Stream<_i8.SessionEndReason> get onLogout =>
      (super.noSuchMethod(
            Invocation.getter(#onLogout),
            returnValue: _i4.Stream<_i8.SessionEndReason>.empty(),
          )
          as _i4.Stream<_i8.SessionEndReason>);

  @override
  void expireSession() => super.noSuchMethod(
    Invocation.method(#expireSession, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyLogin() => super.noSuchMethod(
    Invocation.method(#notifyLogin, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyLogout(_i8.SessionEndReason? reason) => super.noSuchMethod(
    Invocation.method(#notifyLogout, [reason]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
