name: Sonar-Qube
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: read
  statuses: write

jobs:
  sonarcloud:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install dependencies and Test
        run: |
          flutter pub get
          # لو عندك Code Generation فك الكومنت عن السطر اللي جاي:
          # flutter pub run build_runner build --delete-conflicting-outputs
          flutter test --coverage 
          
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=MoHa270xX_Flowers-App
            -Dsonar.organization=moha270xx
            -Dsonar.dart.lcov.reportPath=coverage/lcov.info
            -Dsonar.sources=lib
            -Dsonar.tests=test
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.head_ref }}
            -Dsonar.pullrequest.base=${{ github.base_ref }}